name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: |
          corepack prepare pnpm@9.15.0 --activate
          pnpm install

      - name: Deploy
        env:
          ANOTHER_REPO_TOKEN: ${{ secrets.ANOTHER_REPO_TOKEN }}
        run: bash tools/deploy.sh
